Remove blueprints for view and view-test
They are removed in ember-cli as of 2.4.3 https://github.com/ember-cli/ember-cli/pull/5607
And having them in ember-cli-coffeescript gives errors if using a never version of ember-cli in the same project

```
Cannot find module 'ember-cli/blueprints/view'
Error: Cannot find module 'ember-cli/blueprints/view'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/mriska/work/test3/node_modules/ember-cli-coffeescript/blueprints/view/index.js:1:80)
```